FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY CourseRegistrationSystemBackEnd ./backend

WORKDIR /app/backend

RUN chmod +x mvnw && ./mvnw clean package -DskipTests

CMD ["sh", "-c", "java -jar target/*.jar"]