FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY CourseRegistrationSystemBackEnd ./backend

WORKDIR /app/backend

RUN chmod +x mvnw && ./mvnw clean package -DskipTests

CMD ["java", "-jar", "target/*.jar"]