FROM maven:3.9.9-eclipse-temurin-17

WORKDIR /app

COPY CourseRegistrationSystemBackEnd ./CourseRegistrationSystemBackEnd

WORKDIR /app/CourseRegistrationSystemBackEnd

RUN mvn clean package -DskipTests

CMD ["java", "-jar", "target/*.jar"]